data:
  image: python:3.9
  volumes:
    - ./:/app
    - ./data:/data

# shares volume with other images so we can use COPY
db:
  image: mdillon/postgis:9.6
  environment:
    - POSTGRES_USER=gnaf
    - POSTGRES_PASSWORD=gnaf
  volumes_from:
    - data

loader:
  build: .
  volumes_from:
    - data
  links:
   - db
  ports:
    - "9000"
